### ISSUE TITLE
Colour Scheme

### ISSUE THREAD

**Issue by CrazyEggz** [CrazyEggz/ci-hackthon2-quiz-frenzy#7]
To come up with a colour scheme/ mood board for the website.

**Comment by CrazyEggz** [comment]
The colour scheme selected for the website should be bright and joyful.
(The background colour is #fff9ef)

![image](https://github.com/CrazyEggz/ci-hackthon2-quiz-frenzy/assets/169710266/cdfbbdca-ff9a-4eef-b83d-4ee92e872da4)

**Comment by Spencily** [comment]
https://mycolor.space/?hex=%23BB95E7&sub=1

This site might be helpful for us
