### ISSUE TITLE
USER STORY: Player Name

### ISSUE THREAD

**Issue by ajbecks** [CrazyEggz/ci-hackthon2-quiz-frenzy#9]
As a user, I want to enter my name before starting the quiz so that my name can be displayed with my score at the end.

 Acceptance Criteria:
        •       Before the quiz starts, there is a field for the user to enter their name.
        •       The name entered is displayed at the start of the quiz (e.g., “Welcome, [Name]!”).
        •       At the end of the quiz, the user’s name is displayed along with their score (e.g., “[Name], your score is 8/10”).
        •       If the user does not enter a name, a default name (e.g., “Player”) is used.

**Comment by Spencily** [comment]
I have created the functionality for the page to change after the name is entered and will work on adding the name to the categories page.
